// Blog post manifest — single source of truth for routing, blog index, and sitemap generation.
export const POSTS = [
  {
    slug: 'enable-location-on-windows-and-mac',
    title: 'How to Turn On Location on a Laptop (Windows 10, 11 & Mac)',
    excerpt:
      'Turn on location on any laptop — Windows 10, Windows 11, or Mac. Enable Location Services, allow your browser, and fix the greyed-out toggle on a work laptop.',
    date: '2026-06-03',
    readingTime: 9,
    tags: ['troubleshooting', 'desktop', 'browser'],
  },
  {
    slug: 'enable-location-on-iphone-and-android',
    title: 'How to Turn On Location Services on iPhone & Android',
    excerpt:
      "Enable Location Services on iPhone and Android, fix per-app and per-site permissions, turn on Precise Location, and beat the battery-saver gotcha.",
    date: '2026-06-03',
    readingTime: 9,
    heroImage: 'enable-location-on-iphone-and-android-hero.jpg',
    tags: ['troubleshooting', 'mobile', 'privacy'],
  },
  {
    slug: 'history-of-latitude-and-longitude',
    title: 'History of Latitude and Longitude — Sextants to Satellites',
    excerpt:
      'How a Greek scholar, a Yorkshire clockmaker, and a global voting conference in 1884 produced the two numbers your phone shows you today.',
    date: '2026-06-01',
    readingTime: 7,
    heroImage: 'history-of-latitude-and-longitude-hero.jpg',
    tags: ['history', 'coordinates', 'gps'],
  },
  {
    slug: 'why-maps-show-wrong-street',
    title: 'Why your maps app sometimes puts you on the wrong street',
    excerpt:
      'Five reasons the pin lands at the wrong door — interpolated house numbers, mislabelled buildings, and new streets the database has not caught up with.',
    date: '2026-05-30',
    readingTime: 8,
    heroImage: 'why-maps-show-wrong-street-hero.jpg',
    tags: ['maps', 'troubleshooting', 'addresses'],
  },
  {
    slug: 'what-your-ip-reveals',
    title: 'What does my IP address really tell apps about me?',
    excerpt:
      'A plain-language look at what an IP lookup actually returns, what it does not, and why mobile data and VPNs make the city wrong so often.',
    date: '2026-05-28',
    readingTime: 7,
    heroImage: 'what-your-ip-reveals-hero.jpg',
    tags: ['ip', 'privacy'],
  },
  {
    slug: 'gps-coordinates-emergencies-aml-guide',
    title: 'GPS Coordinates in an Emergency — Send Your Location to 911',
    excerpt: 'How to send GPS coordinates to a 911 or 112 dispatcher: what AML does automatically, the script to say on the call, and how to read them off any phone.',
    date: '2026-05-20',
    readingTime: 12,
    heroImage: 'gps-coordinates-emergencies-aml-guide-hero.jpg',
    tags: ['emergency', 'gps', 'safety'],
  },
  {
    slug: 'browser-geolocation-api-explained',
    title: 'Browser Geolocation API — What Websites Can and Can\'t See',
    excerpt: 'A walkthrough of navigator.geolocation: how it works, what the OS fuses into a coordinate, the permission model, and the privacy implications.',
    date: '2026-05-19',
    readingTime: 9,
    tags: ['geolocation', 'api', 'privacy'],
  },
  {
    slug: 'how-to-share-gps-location-safely',
    title: 'Share Your Location Safely — WhatsApp, Maps & Signal',
    excerpt: 'Compare WhatsApp, iMessage, Google Maps and Signal for sharing your location. What each leaks, which duration to pick, and how to stop a share.',
    date: '2026-05-18',
    readingTime: 10,
    heroImage: 'how-to-share-gps-location-safely-hero.jpg',
    tags: ['privacy', 'sharing', 'safety'],
  },
  {
    slug: 'how-to-find-your-gps-coordinates',
    title: 'How to Find Your GPS Coordinates on Any Device (2026)',
    excerpt: 'The fastest, most accurate ways to get your exact latitude and longitude — on iPhone, Android, Mac, Windows, and any browser. With privacy tips and free tools.',
    date: '2026-05-13',
    readingTime: 7,
    tags: ['gps', 'coordinates', 'guide'],
  },
  {
    slug: 'what-is-ip-location-and-how-accurate',
    title: 'What Is IP Location, and How Accurate Is It Really?',
    excerpt: 'Country accuracy 95–99%, city 50–75%, street level basically zero. The real numbers behind IP geolocation and why mobile and VPN break it.',
    date: '2026-05-12',
    readingTime: 10,
    heroImage: 'what-is-ip-location-and-how-accurate-hero.jpg',
    tags: ['ip', 'geolocation', 'privacy'],
  },
  {
    slug: 'latitude-vs-longitude-explained',
    title: 'Latitude vs Longitude — Which Is Which, and How to Remember',
    excerpt: 'Which is which, the order in coordinates, signs, decimal precision, the three formats you will meet, and the antimeridian bug that breaks naive code.',
    date: '2026-05-11',
    readingTime: 8,
    heroImage: 'latitude-vs-longitude-explained-hero.jpg',
    tags: ['coordinates', 'basics', 'guide'],
  },
  {
    slug: 'how-gps-works',
    title: 'How GPS Works: From Satellites to Your Phone',
    excerpt: 'A clear, no-buzzword walkthrough of how satellites 20,000 km overhead let your phone know exactly where you are — and what can go wrong.',
    date: '2026-05-10',
    readingTime: 9,
    heroImage: 'how-gps-works-hero.jpg',
    tags: ['gps', 'satellites', 'technology'],
  },
  {
    slug: '10-uses-for-gps-coordinates',
    title: '10 Surprising Uses for GPS Coordinates in Everyday Life',
    excerpt: 'From geocaching to verifying VPNs to precision farming — ten practical things you can do once you know how to read your own latitude and longitude.',
    date: '2026-05-09',
    readingTime: 6,
    heroImage: '10-uses-for-gps-coordinates-hero.jpg',
    tags: ['gps', 'use-cases', 'guide'],
  },
];

export const findPost = (slug) => POSTS.find((p) => p.slug === slug);
