// Blog post manifest — single source of truth for routing, blog index, and sitemap generation.
export const POSTS = [
  {
    slug: 'enable-location-on-windows-and-mac',
    topic: 'permissions', // groups the post on the blog index
    title: 'How to Turn On Location on a Laptop (Windows 10, 11 & Mac)',
    excerpt:
      'Windows 11: Settings → Privacy & security → Location → On (Windows 10: Privacy → Location). Mac: Privacy & Security → Location Services.',
    date: '2026-06-03',
    modifiedDate: '2026-10-05',
    readingTime: 9,
    tags: ['troubleshooting', 'desktop', 'browser'],
  },
  {
    slug: 'enable-location-on-iphone-and-android',
    topic: 'permissions',
    title: 'How to Turn On Location Services on iPhone & Android',
    excerpt:
      'Turn on Location Services on iPhone and Android, allow Safari or Chrome to use it, fix website permissions and Precise Location. Updated for 2026.',
    date: '2026-06-03',
    modifiedDate: '2026-10-05',
    readingTime: 10,
    heroImage: 'enable-location-on-iphone-and-android-hero.jpg',
    tags: ['troubleshooting', 'mobile', 'privacy'],
  },
  {
    slug: 'history-of-latitude-and-longitude',
    topic: 'gps',
    title: 'History of Latitude and Longitude — Sextants to Satellites',
    excerpt:
      'How a Greek scholar, a Yorkshire clockmaker, and a global voting conference in 1884 produced the two numbers your phone shows you today.',
    date: '2026-06-01',
    modifiedDate: '2026-06-01',
    readingTime: 7,
    heroImage: 'history-of-latitude-and-longitude-hero.jpg',
    tags: ['history', 'coordinates', 'gps'],
  },
  {
    slug: 'why-maps-show-wrong-street',
    topic: 'maps',
    title: 'Why your maps app sometimes puts you on the wrong street',
    excerpt:
      'Five reasons the pin lands at the wrong door — interpolated house numbers, mislabelled buildings, and new streets the database has not caught up with.',
    date: '2026-05-30',
    modifiedDate: '2026-10-01',
    readingTime: 8,
    heroImage: 'why-maps-show-wrong-street-hero.jpg',
    tags: ['maps', 'troubleshooting', 'addresses'],
  },
  {
    slug: 'what-your-ip-reveals',
    topic: 'ip',
    title: 'What does my IP address really tell apps about me?',
    excerpt:
      'A plain-language look at what an IP lookup actually returns, what it does not, and why mobile data and VPNs make the city wrong so often.',
    date: '2026-05-28',
    modifiedDate: '2026-10-01',
    readingTime: 7,
    heroImage: 'what-your-ip-reveals-hero.jpg',
    tags: ['ip', 'privacy'],
  },
  {
    slug: 'gps-coordinates-emergencies-aml-guide',
    topic: 'gps',
    title: 'GPS Coordinates in an Emergency — Send Your Location to 911',
    excerpt: 'How to give GPS coordinates to a 911 or 112 dispatcher: what AML sends automatically, what to say on the call, and how to read them off any phone.',
    date: '2026-05-20',
    modifiedDate: '2026-05-20',
    readingTime: 12,
    heroImage: 'gps-coordinates-emergencies-aml-guide-hero.jpg',
    tags: ['emergency', 'gps', 'safety'],
  },
  {
    slug: 'browser-geolocation-api-explained',
    topic: 'permissions',
    title: 'Browser Geolocation API: What Websites Can and Can\'t See',
    excerpt: 'How navigator.geolocation works: getCurrentPosition, watchPosition, options, accuracy, error codes and permissions, with code you can copy.',
    date: '2026-05-19',
    modifiedDate: '2026-10-06',
    readingTime: 10,
    tags: ['geolocation', 'api', 'privacy'],
  },
  {
    slug: 'how-to-share-gps-location-safely',
    topic: 'permissions',
    title: 'Share Your Location Safely: WhatsApp, iPhone, Google Maps',
    excerpt: 'Share your live location without oversharing: who can see it, how long it lasts, and how to stop it on WhatsApp, iPhone, Google Maps and Messages.',
    date: '2026-05-18',
    modifiedDate: '2026-10-05',
    readingTime: 12,
    heroImage: 'how-to-share-gps-location-safely-hero.jpg',
    tags: ['privacy', 'sharing', 'safety'],
  },
  {
    slug: 'how-to-find-your-gps-coordinates',
    topic: 'gps',
    title: 'How to Find Your GPS Coordinates on Any Device (2026)',
    excerpt: 'The fastest ways to get your exact latitude and longitude on iPhone, Android, Mac, Windows, or any browser, with accuracy and privacy tips.',
    date: '2026-05-13',
    modifiedDate: '2026-10-05',
    readingTime: 7,
    tags: ['gps', 'coordinates', 'guide'],
  },
  {
    slug: 'what-is-ip-location-and-how-accurate',
    topic: 'ip',
    title: 'What Is IP Location, and How Accurate Is It Really?',
    excerpt: 'IP location gets the country right 99.8% of the time but often misses the city. The real accuracy figures, and why mobile networks and VPNs break it.',
    date: '2026-05-12',
    modifiedDate: '2026-10-05',
    readingTime: 10,
    heroImage: 'what-is-ip-location-and-how-accurate-hero.jpg',
    tags: ['ip', 'geolocation', 'privacy'],
  },
  {
    slug: 'latitude-vs-longitude-explained',
    topic: 'gps',
    title: 'Latitude vs Longitude — Which Is Which, and How to Remember',
    excerpt: 'Which is which, the order in coordinates, signs, decimal precision, the three formats you will meet, and the antimeridian bug that breaks naive code.',
    date: '2026-05-11',
    modifiedDate: '2026-05-11',
    readingTime: 8,
    heroImage: 'latitude-vs-longitude-explained-hero.jpg',
    tags: ['coordinates', 'basics', 'guide'],
  },
  {
    slug: 'how-gps-works',
    topic: 'gps',
    title: 'How GPS Works: From Satellites to Your Phone',
    excerpt: 'A clear, no-buzzword walkthrough of how satellites 20,000 km overhead let your phone know exactly where you are — and what can go wrong.',
    date: '2026-05-10',
    modifiedDate: '2026-05-10',
    readingTime: 9,
    heroImage: 'how-gps-works-hero.jpg',
    tags: ['gps', 'satellites', 'technology'],
  },
  {
    slug: '10-uses-for-gps-coordinates',
    topic: 'gps',
    title: '10 Surprising Uses for GPS Coordinates in Everyday Life',
    excerpt: 'From geocaching to verifying VPNs to precision farming — ten practical things you can do once you know how to read your own latitude and longitude.',
    date: '2026-05-09',
    modifiedDate: '2026-05-09',
    readingTime: 6,
    heroImage: '10-uses-for-gps-coordinates-hero.jpg',
    tags: ['gps', 'use-cases', 'guide'],
  },
];

export const findPost = (slug) => POSTS.find((p) => p.slug === slug);
